project:
  type: book
  output-dir: docs

book:
  title: "Séries Temporais"
  author: "James D Santos"
  date: "28/09/2023"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - ts_window_date.qmd
    - estacionaria.qmd
    - acf.qmd
    - modelo_linear.qmd
    - tendencia.qmd
    - sazonalidade.qmd
    - tendencia_sazonalidade.qmd
    - suave_exponencial.qmd
    - processo_linear_geral.qmd
    - intervencao.qmd
    - regressao.qmd
    - longa_memoria.qmd
    - garch.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
 