project:
  type: book
  output-dir: docs

book:
  title: "Series temporais"
  author: "James D Santos"
  date: "02/12/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - estacionaria.qmd
    - acf.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
