project:
  type: book
  output-dir: docs

book:
  title: "Séries Temporais"
  author: "James D Santos"
  date: "02/12/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - estacionaria.qmd
    - acf.qmd
    - ts_window_date.qmd
    - modelo_linear.qmd
    - tendencia.qmd
    - sazonalidade.qmd
    - tendencia_sazonalidade.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
