# Séries Estacionárias

Uma coleção do tipo $\{x(t),t\in\mathcal{T}\}$, $\mathcal{T}\subseteq \mathbb{R}$, onde $x(t)$ é uma variável aleatória para cada $t$ fixado,  é denominada processo estocástico.

Quando o conjunto de índices $\mathcal{T}$ é discreto, utilizamos a notação $x_t$ no lugar de $x(t)$. A partir deste momento, estamos interessados apenas em processos com o conjunto de índices discreto. Também utilizaremos a notação $x_t$ tanto para a variável aleatória quanto para o valor do processo no índice  $t$.   

Um processo estocástico é dito ser fortemente estacionário (ou de primeira ordem) se sua distribuição é invariante ao índice. Portanto, para qualquer $t_1,\ldots,t_k$, a distribuição de $x_{t_1},\ldots,x_{t_k}$ é a mesma de $x_{t_1+h},\ldots,x_{t_k+h}$.  

:::{#exm-serie_estacionaria_1}
Se $x_t\sim \hbox{Normal}(0,1)$ e $x_t$ é independente de $x_s$ para todo $t\neq s$, então, para qualquer $t_1,\ldots,t_k$,

$$\begin{align}P(x_{t_1}<x_1,\ldots,x_{t_k}<x_k)&=\prod_{i=1}^k P(x_{t_i}<x_i)=\prod_{i=1}^k P(x_{t_i+h}<x_i)\\&=P(x_{t_1+h}<x_1,\ldots,x_{t_k+h}<x_k)\end{align}$$
logo, $\{x_t,t\in \mathbb{N}\}$ é um processo fortemente estacionário. Note que, o mesmo resultado se aplica para qualquer amostra aleatória.
$\blacksquare$
:::


:::{#thm-exm_estacionaria2}
Seja $\{x_t,t\in\mathbb{N}\}$ um processo estocástico com 
	$$x_t= x_{t-1}+\varepsilon_t,\;\;\varepsilon_t\sim\hbox{Normal}(0,1),$$
para $t=1,2,\ldots$ com a condição de que $x_0\sim\hbox{Normal}(0,1)$ e que $Cov(\varepsilon_t,\varepsilon_s)=0\;\;\forall s\neq t$.
	Então,
	$$x_t=x_{t-1}+\varepsilon_{t}=\cdots=x_0+\sum_{j=1}^t\varepsilon_j\sim\hbox{Normal}(0,t+1).$$
	Como $x_t\sim\hbox{Normal}(0,t+1)$ e, para qualquer $h>0$, $x_{t+h}\sim\hbox{Normal}(0,t+h+1)$, temos que este processo não é fortemente estacionário.
$\blacksquare$
:::


::: {#def-fracamente}
Um processo estocástico $\{y_t\}$ é dito ser fracamente estacionário (ou de segunda ordem) se 
$$\begin{align*}
	E(y_t)&=\mu,\\
	Var(y_t)&=\nu,\\ 
	Cov(y_t,y_s)&=E(y_ty_s)-E(y_t)E(y_s)=\gamma(t-s)
	\end{align*}$$
onde $\mu$ e $\nu$ são constantes independentes de $t$ e $\gamma(t-s)$ depende de $t$ e $s$ somente através da diferença $|t-s|$.
$\blacksquare$
:::
				

:::{#exm-fracamente1}
Considere o processo estocástico $\{x_t,t\in\mathbb{N}\}$, onde 
$$x_t = \varepsilon_t +\frac{1}{2}\varepsilon_{t-1}
$$
onde $\varepsilon_t\sim\hbox{Normal}(0,\nu)$ para $t=1,\ldots$, $\varepsilon_t$ é independente de $\varepsilon_s$ para todo $s\neq t$ e $\varepsilon_0=0$.
Então:
$$\begin{align}
E(x_t)&=E(\varepsilon_t)+\frac{1}{2}E(\varepsilon_{t-1})=0\\
Var(x_t)&=Var(\varepsilon_t)+\frac{1}{4}Var(\varepsilon_{t-1})=\frac{5}{4}\nu
\end{align}
$$
e
$$\begin{align}
		  Cov(x_t,x_{t+h})&=Cov\left(\varepsilon_t+\frac{1}{2}\varepsilon_{t-1},\varepsilon_{t+h}+\frac{1}{2}\varepsilon_{t+h-1}\right)\\
		  &=Cov\left(\varepsilon_t,\varepsilon_{t+h}\right)+\frac{1}{2}Cov\left(\varepsilon_t,\varepsilon_{t+h-1}\right)\\
		  &+\frac{1}{2}Cov\left(\varepsilon_{t-1},\varepsilon_{t+h}\right)+\frac{1}{4}Cov\left(\varepsilon_{t-1},\varepsilon_{t+h-1}\right)\\
		  &=\left\{ \begin{array}{ll}
		  \frac{5}{4}\nu,&\; h = 0 \\		  
		  \frac{1}{2}\nu,&\; |h|=1,\\
		  0,&\;\hbox{caso contrário.}
		  \end{array} \right.
	\end{align}$$
Portanto, o processo é fracamente estacionário.
$\blacksquare$
:::

Quando o conjunto de índices representa o tempo, o processo estocástico é denominado série temporal. Uma série temporal é dita ser estacionária se ela é fracamente estacionária.  


## Processo estacionário ergódico

Seja $x_1,x_2,\ldots,x_n$ uma série temporal estacionária. Então, a média $\mu$ pode ser estimada por $\bar{x}_n$, uma vez que $E(\bar{x})=\mu$. A variância dessa estatística  é

$$\begin{align}Var(\bar{x})&=Cov(\bar{x}_n,\bar{x}_n)=Cov\left(\sum_{i=1}^n \frac{x_i}{n},\sum_{j=1}^n\frac{x_j}{n}\right)=\frac{1}{n^2}\sum_{i=1}^n\sum_{j=1}^nCov(x_i,x_j)\\
&=\frac{1}{n^2}\left[\sum_{i=1}^nCov(x_i,x_i)+\sum_{i=1}^n\sum_{j\neq i}Cov(x_i,x_j)\right]\\
&=\frac{1}{n^2}\left[n\nu+2\sum_{h=1}^{n-1}(n-h)\gamma(h)\right]=\frac{\nu}{n}+\frac{2}{n}\sum_{h=1}^{n-1}\left(1-\frac{h}{n}\right)\gamma(h)
\end{align}$$
	
Note que, diferente do caso independente e identicamente distribuído, $\bar{x}_n$ não é necessariamente um estimador adequado, conforme pode ser constatado no exemplo abaixo.


:::{#exm-estationario_nao_ergodico}
Seja $x_t$ um processo onde $x_0\sim\hbox{Normal}(0,\nu)$ e $x_t=x_0$ para todo $t>0$. Como

$$\begin{align}
E(x_t)&=E(E(x_t|x_0))=E(x_0)=0\\
Var(x_t)&=E(Var(x_t|x_0))+Var(E(x_t|x_0))=E(0)+Var(x_0)=\nu\\
Cov(x_t,x_{t-h})&=E( Cov(x_t,x_{t-h}|x_0))+Cov( E(x_t|x_0),E(x_{t-h}|x_0))\\
&=E(0)+Cov(x_0,x_0)=Var(x_0)=\nu
\end{align}$$
e, portanto, o processo é fracamente estacionário. Contudo, 
$$Var(\bar{x}_n)=\frac{\nu}{n}+\frac{2}{n}\sum_{h=1}^{n-1}\left(1-\frac{h}{n}\right)\nu=\nu,$$
portanto, o erro padrão não decai com o aumento do tamanho da amostra. 

$\blacksquare$
:::

A partir do exemplo acima, fica claro que $\bar{x}_n$ nem sempre será um estimador adequado para uma série estacionária. 

::: {#def-ergodica}
Uma série temporal estacionária é dita ser ergódica para a média se
$$\sum_{t=1}^n\frac{x_t}{n}\stackrel{P}{\rightarrow} \mu,$$
quando $n\rightarrow\infty$.
:::

A partir deste momento **será considerado que toda série temporal estacionária é ergódica** e, portanto $\bar{x}$ é um estimador para $\mu$. 

:::{#exm-estationario_nao_ergodico_conclusao}

Considere novamente o processo no @exm-estationario_nao_ergodico. Como
$\bar{x}_n=x_0$, tem-se que, para $\varepsilon>0$ arbitrário, $\bar{x}\sim\hbox{Normal}(0,\nu)$ e 
$$P(|\bar{x}_n-0|>\varepsilon)=2P(x_0>\varepsilon)=2\int_\varepsilon^{\infty} \frac{1}{\sqrt{2\pi\nu}}e^{-\frac{y^2}{2\nu}}dy>0,\quad \forall n$$
logo, $\bar{x}$ não converge em probabilidade para $0$ e, portanto, o processo não é ergódico na média.
$\blacksquare$
:::


## Ruído branco

:::{#def-ruido_branco}
A série estacionária $x_t$ é dita ser um ruído branco se $E(x_t)=0$, $Var(x_t)=\nu$ e
		$$\begin{equation}
		Cov(x_t,x_s)=0,
		\end{equation}$$
para todo $t\neq s$.
$\blacksquare$
::: 

É imediato que o ruído branco é uma série temporal estacionária. Além disso, pela Desigualdade de Chebyshev, para qualquer $\varepsilon>0$, 

$$P\left(|\bar{x}_n|\geq\varepsilon\right)\leq \frac{E(\bar{x}_n^2)}{\varepsilon^2}=\frac{Var(\bar{x}_n)}{\varepsilon^2}=\frac{\nu}{n\varepsilon^2}$$
logo $\lim_{n}P(|\bar{x}_n|\geq \varepsilon)=0$ e $\bar{x}_n\stackrel{p}{\rightarrow}0$. Portanto, o ruído branco é ergódico.

Considere agora a série temporal $y_t=\mu+x_t$, onde $x_t$ é um ruído branco. Então 
$$\bar{y}_n=\mu+\bar{x}_n\stackrel{p}{\rightarrow}\mu$$
e $\bar{y}_n$ é um estimador para $\mu$.

Em certos momentos, será considerado que $x_t$ e $x_s$, para todo $t\neq s$ são independentes (essa é uma condição mais forte, pois implica em $Cov(x_t,x_s)=0$). Esse processo é denominado ruído branco independente.

Por último, também será considerada a possibilidade de que $x_t\sim\hbox{Normal}(0,\nu)$, com $x_t$ e $x_s$ independentes para todo $t\neq s$. Esse processo é denominado ruído branco gaussiano. 