<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Métodos de suavização exponencial – Séries Temporais</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./processo_linear_geral.html" rel="next">
<link href="./state_space.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c574c73dd0d0ff61020859ffc61752ee.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./suave_exponencial.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Métodos de suavização exponencial</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Séries Temporais</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introdução</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ts_window_date.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Criando séries no <code>R</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estacionaria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Séries Estacionárias</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Defasagens e autocorrelação</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modelo_linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Revisão sobre o modelo linear</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tendencia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Tendência</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sazonalidade.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sazonalidade</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./state_space.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modelos de Espaço de Estados Lineares</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./suave_exponencial.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Métodos de suavização exponencial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./processo_linear_geral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modelos ARMA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intervencao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Intervenção e outliers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regressao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Modelos de regressão para séries temporais</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./longa_memoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Séries de longa memória</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./garch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Modelos heterocedásticos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#suavização-exponencial-simples" id="toc-suavização-exponencial-simples" class="nav-link active" data-scroll-target="#suavização-exponencial-simples"><span class="header-section-number">10.1</span> Suavização exponencial simples</a></li>
  <li><a href="#suavização-exponencial-de-holt" id="toc-suavização-exponencial-de-holt" class="nav-link" data-scroll-target="#suavização-exponencial-de-holt"><span class="header-section-number">10.2</span> Suavização exponencial de Holt</a></li>
  <li><a href="#suavização-exponencial-de-holt-winters" id="toc-suavização-exponencial-de-holt-winters" class="nav-link" data-scroll-target="#suavização-exponencial-de-holt-winters"><span class="header-section-number">10.3</span> Suavização exponencial de Holt-Winters</a></li>
  <li><a href="#modelo-de-espaço-de-estados-com-inovações" id="toc-modelo-de-espaço-de-estados-com-inovações" class="nav-link" data-scroll-target="#modelo-de-espaço-de-estados-com-inovações"><span class="header-section-number">10.4</span> Modelo de espaço de estados com inovações</a>
  <ul class="collapse">
  <li><a href="#suavização-exponencial-simples-1" id="toc-suavização-exponencial-simples-1" class="nav-link" data-scroll-target="#suavização-exponencial-simples-1"><span class="header-section-number">10.4.1</span> Suavização exponencial simples</a></li>
  <li><a href="#suavização-exponencial-de-holt-1" id="toc-suavização-exponencial-de-holt-1" class="nav-link" data-scroll-target="#suavização-exponencial-de-holt-1"><span class="header-section-number">10.4.2</span> Suavização Exponencial de Holt</a></li>
  <li><a href="#suavização-exponencial-de-holt-winters-1" id="toc-suavização-exponencial-de-holt-winters-1" class="nav-link" data-scroll-target="#suavização-exponencial-de-holt-winters-1"><span class="header-section-number">10.4.3</span> Suavização Exponencial de Holt-Winters</a></li>
  </ul></li>
  <li><a href="#exercício" id="toc-exercício" class="nav-link" data-scroll-target="#exercício"><span class="header-section-number">10.5</span> Exercício</a></li>
  <li><a href="#para-outro-curso" id="toc-para-outro-curso" class="nav-link" data-scroll-target="#para-outro-curso"><span class="header-section-number">10.6</span> Para outro curso…</a>
  <ul class="collapse">
  <li><a href="#modelo-de-holt-amortecido" id="toc-modelo-de-holt-amortecido" class="nav-link" data-scroll-target="#modelo-de-holt-amortecido"><span class="header-section-number">10.6.1</span> Modelo de Holt amortecido</a></li>
  </ul></li>
  <li><a href="#modelos-com-componentes-multiplicativas" id="toc-modelos-com-componentes-multiplicativas" class="nav-link" data-scroll-target="#modelos-com-componentes-multiplicativas"><span class="header-section-number">10.7</span> Modelos com componentes multiplicativas</a>
  <ul class="collapse">
  <li><a href="#tendência-multiplicativa" id="toc-tendência-multiplicativa" class="nav-link" data-scroll-target="#tendência-multiplicativa"><span class="header-section-number">10.7.1</span> Tendência multiplicativa</a></li>
  <li><a href="#tendência-aditiva-e-sazonalidade-multiplicativa" id="toc-tendência-aditiva-e-sazonalidade-multiplicativa" class="nav-link" data-scroll-target="#tendência-aditiva-e-sazonalidade-multiplicativa"><span class="header-section-number">10.7.2</span> Tendência aditiva e sazonalidade multiplicativa</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Métodos de suavização exponencial</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Métodos de suavização exponencial são, em princípio, modelos semi-paramétricos com o objetivo de suavizar o sinal para o tempo <span class="math inline">\(t\)</span> utilizando toda a amostra <span class="math inline">\(\mathcal{D}_t\)</span> através de uma média ponderada.</p>
<p>Inicialmente, apenas as ideias originais serão apresentadas, de modo que a lógica por trás dos métodos seja compreendida. Durante essas apresentações, não faremos aplicações.</p>
<p>Por fim, mostraremos que os modelos de suavização exponencial podem ser escritos na forma de modelos de espaço de estados, apresentando sua estrutura e formas de previsão. Em seguida, as aplicações são apresentadas, utilizando o pacote <code>forecast</code>, que apresenta as implementações destes modelos neste formato final.</p>
<section id="suavização-exponencial-simples" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="suavização-exponencial-simples"><span class="header-section-number">10.1</span> Suavização exponencial simples</h2>
<p>Considere uma série temporal descrita como</p>
<p><span class="math display">\[x_t=\mu_t+\varepsilon_t,\]</span> onde <span class="math inline">\(\mu_t\)</span> é a média da série, denominada nível, para o tempo <span class="math inline">\(t\)</span>. Para esse modelo, é assumido que <span class="math inline">\(\mu_t\)</span> pode oscilar, mas não ao ponto de criar qualquer sinal como uma tendência ou sazonalidade. Para a amostra <span class="math inline">\(\mathcal{D}_t\)</span>, o modelo de suavização exponencial simples propõe estimar <span class="math inline">\(\mu_t\)</span> por uma média ponderada dos valores passados, dada por</p>
<p><span class="math display">\[\mu_t=\alpha x_t+\sum_{j=1}^{t-1}\alpha(1-\alpha)^jx_{t-j},\]</span> onde <span class="math inline">\(\alpha\in(0,1)\)</span>. A constante <span class="math inline">\(\alpha\)</span> deve ser grande o suficiente para que os valores passados não tenha tanta influência, mas não tão grande ao ponto de ser influenciada em excesso pelo erro associado à observação <span class="math inline">\(x_t\)</span>.</p>
<p>Observe que</p>
<p><span class="math display">\[\begin{aligned}\mu_t&amp;=\alpha x_t+\alpha\sum_{j=1}^{t-1}(1-\alpha)^jx_{t-j}\\&amp;=\alpha x_t+(1-\alpha)\left[\alpha x_{t-1}+\sum_{j=2}^{t-1}\alpha(1-\alpha)^{j-1}x_{t-j}\right]\\&amp;=\alpha x_t+(1-\alpha)\left[\alpha x_{t-1}+\alpha \sum_{j=1}^{t-2}(1-\alpha)^{j}x_{t-1-j}\right]\\&amp;=\alpha x_t+(1-\alpha)\mu_{t-1}\end{aligned}\]</span></p>
<p>logo, <span class="math inline">\(\mu_t\)</span> pode ser obtido de modo recursivo.</p>
<p>O modelo de suavização exponencial segue a seguinte lógica:</p>
<ol type="1">
<li>Para <span class="math inline">\(t=0\)</span>, inicie com os valores <span class="math inline">\(\mu_0\)</span> e <span class="math inline">\(\alpha\)</span>.</li>
<li>Para <span class="math inline">\(t=1,\ldots,n\)</span>:</li>
</ol>
<ol type="a">
<li>Calcule o erro de previsão <span class="math inline">\(e_t =x_t-f_t=x_t-\mu_{t-1}\)</span></li>
<li>Estime <span class="math inline">\(\mu_t\)</span> através de <span class="math display">\[\mu_t=\alpha x_t+(1-\alpha)\mu_{t-1}.\]</span></li>
</ol>
<p>Como é esperado que o erro de previsão seja um ruído branco, <span class="math inline">\(\mu_0\)</span> e <span class="math inline">\(\alpha\)</span> podem ser estimados minimizando numericamente <span class="math display">\[\sum_{t=1}^n e_t^2.\]</span></p>
<p>Para esse modelo a previsão <span class="math inline">\(f_t=E(x_t|\mathcal{D}_{t-1})\)</span> é dada pelo último nível estimado no tempo <span class="math inline">\(t-1\)</span>, ou seja <span class="math inline">\(\mu_{t-1}\)</span>. Portanto, a equação recursiva pode ser pensada como a combinação linear convexa de duas fontes de informação, uma proveniente da amostra no tempo <span class="math inline">\(t\)</span> e outra disponível no tempo <span class="math inline">\(t-1\)</span>:</p>
<p><span class="math display">\[\mu_t=\alpha\underbrace{x_t}_{\text{informação\\da amostra\\no tempo }t}+(1-\alpha)\underbrace{\mu_{t-1}}_{\substack{\text{estimativa para }}\mu_t\text{\\disponível no \\tempo }t-1}\]</span> Essa composição da estimativa através da combinação de duas fontes de informação é útil para entender os próximos modelos.</p>
</section>
<section id="suavização-exponencial-de-holt" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="suavização-exponencial-de-holt"><span class="header-section-number">10.2</span> Suavização exponencial de Holt</h2>
<p>Considere agora um modelo da forma <span class="math display">\[x_t = \mu_t + \varepsilon_t,\]</span> onde <span class="math inline">\(\mu_t\)</span> é o nível e <span class="math inline">\(\varepsilon_t\)</span> o ruído branco. Adicionalmente, considere que o modelo possui tendência. Uma função de previsão razoável para este problema é</p>
<p><span class="math display">\[f_t(h)=E(x_{t+h}|\mathcal{D}_t)=\mu_t+h\xi_t,\]</span> onde <span class="math inline">\(\xi_t\)</span> é o parâmetro de tendência. Ele recebe esse nome porque, quando nulo, o modelo é livre de tendência. Além disso, dependendo do seu sinal, a tendência será crescente ou decrescente.</p>
<p>Temos duas fontes de informação sobre <span class="math inline">\(\mu_t\)</span>:</p>
<ol type="1">
<li><p>A própria amostra, pois <span class="math inline">\(x_t\)</span> oscila em torno de <span class="math inline">\(\mu_t\)</span></p></li>
<li><p>A previsão para <span class="math inline">\(x_t\)</span> no tempo <span class="math inline">\(t-1\)</span>, dada por <span class="math inline">\(f_{t-1}(1)=\mu_{t-1}+\xi_{t-1}\)</span> e que, por sua vez, é uma previsão para <span class="math inline">\(\mu_t\)</span>.</p></li>
</ol>
<p>Deste modo, assim como visto no modelo de suavização exponencial, temos que <span class="math inline">\(\mu_t\)</span> pode ser obtido a partir da seguinte recursão</p>
<p><span class="math display">\[\begin{aligned*}
    \mu_t &amp;= \alpha x_t + (1-\alpha)\left( \mu_{t-1} + \xi_{t-1}\right).
    \end{aligned*}\]</span></p>
<p>Observe que a recursão só pode ser utilizada se <span class="math inline">\(\xi_t\)</span> for conhecido para todo <span class="math inline">\(t\)</span>. Para construir uma recursão para <span class="math inline">\(\xi_t\)</span>, vamos assumir que <span class="math inline">\(\xi_t\)</span> é a ponderação de duas fontes de informação sobre <span class="math inline">\(\xi_{t-1}\)</span>:</p>
<ol type="1">
<li><p>Para o tempo <span class="math inline">\(t\)</span>, sabemos que <span class="math inline">\(x_t\)</span> é estimativa para <span class="math inline">\(\mu_t\)</span>. Por sua vez, <span class="math inline">\(\mu_t\approx f_{t-1}(1)=\mu_{t-1}+\xi_{t-1}\)</span>. Portanto, <span class="math inline">\(\mu_t-\mu_{t-1}\)</span> é uma estimativa para <span class="math inline">\(\xi_{t-1}\)</span></p></li>
<li><p>Vamos assumir que a inclinação <span class="math inline">\(\xi_t\)</span> oscila pouco, o que implica que <span class="math inline">\(\xi_t\approx \xi_{t-1}\)</span></p></li>
</ol>
<p>Com isso, teremos a seguinte recursão geral para a componentes de nível e tendência</p>
<p><span class="math display">\[\begin{aligned}
    \mu_t &amp;= \alpha x_t + (1-\alpha)\left( \mu_{t-1} + \xi_{t-1}\right) \\
    \xi_t &amp;= \beta (\mu_t - \mu_{t-1}) + (1-\beta)\xi_{t-1}.
    \end{aligned}\]</span> com <span class="math inline">\(\beta\in(0,1)\)</span>. Mais uma vez, os valores para <span class="math inline">\(\xi_0,\mu_0,\alpha\)</span> e <span class="math inline">\(\beta\)</span> podem ser obtidos minimizando a soma de quadrados dos erros de previsão.</p>
</section>
<section id="suavização-exponencial-de-holt-winters" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="suavização-exponencial-de-holt-winters"><span class="header-section-number">10.3</span> Suavização exponencial de Holt-Winters</h2>
<p>Considere o modelo <span class="math display">\[x_t = \mu_t+s_t+\varepsilon_t,\]</span> onde <span class="math inline">\(\mu_t\)</span> é o nível da série e <span class="math inline">\(s_t\)</span> um fator sazonal de período <span class="math inline">\(p\)</span>. Considere ainda que a série possui tendência, localmente linear, gerando uma equação de previsão do tipo</p>
<p><span class="math display">\[f_t(h)=\mu_t+h\xi_t+s_{t+h-p}.\]</span></p>
<p>Para obter estimativas para essas componentes, vamos manter o mesmo princípio de unir fontes de informação através de combinações lineares.</p>
<p>Para obter uma equação recursiva para <span class="math inline">\(\mu_t\)</span>, observe que</p>
<ol type="1">
<li><p>Para o tempo <span class="math inline">\(t\)</span>, como <span class="math inline">\(x_t\)</span> é estimativa para <span class="math inline">\(\mu_t+s_t\)</span>, temos que <span class="math inline">\(x_t-s_t\approx \mu_t\)</span>. Entretanto, como <span class="math inline">\(s_t\)</span> não está disponível ainda, utilizamos <span class="math display">\[x_t-s_{t-p}\approx \mu_t.\]</span></p></li>
<li><p>No tempo <span class="math inline">\(t-1\)</span>, temos que a previsão de <span class="math inline">\(x_t\)</span> é dada por <span class="math display">\[f_{t-1}(1)=\mu_{t-1}+\xi_{t-1}+s_t.\]</span> Como <span class="math inline">\(x_t\)</span> é estimativa para <span class="math inline">\(\mu_t+s_t\)</span>, teremos</p></li>
</ol>
<p><span class="math display">\[\mu_t+s_t\approx\mu_{t-1}+\xi_{t-1}+s_t\Rightarrow\mu_t\approx \mu_{t-1}+\xi_{t-1}\]</span></p>
<p>Desse modo, podemos construir a seguinte equação recursiva</p>
<p><span class="math display">\[\mu_t=\alpha(x_t-s_{t-p})+(1-\alpha)(\mu_{t-1}+\xi_{t-1})\]</span> com <span class="math inline">\(\alpha\in(0,1)\)</span>.</p>
<p>Uma vez que temos o valor suavizado do nível, podemos suavizar a tendência exatamente como foi feito no modelo de Holt: <span class="math display">\[\xi_t =\beta (\mu_t - \mu_{t-1})+ (1-\beta) \xi_{t-1}.\]</span></p>
<p>Vamos agora reunir duas fontes de informação sobre a componente sazonal.</p>
<ol type="1">
<li><p>Podemos descontar o sinal de tendência da série, obtendo assim informações sobre a sazonalidade: <span class="math display">\[x_t - \mu_t\approx s_t.\]</span></p></li>
<li><p>Vamos considerar que a componente sazonal é razoavelmente estável, ou seja <span class="math inline">\(s_{t-p}\approx s_t\)</span> (ou seja, uma oscilação de nível).</p></li>
</ol>
<p>Portanto, obtemos a seguinte recursão</p>
<p><span class="math display">\[\begin{aligned}
    s_t = \gamma (x_t - \mu_t) + (1-\gamma) s_{t-p},
    \end{aligned}\]</span> com <span class="math inline">\(\gamma\in(0,1)\)</span>.</p>
<p>O modelo de Holt-Winters é dado por <span class="math display">\[\begin{aligned}
    \mu_t &amp;=\alpha (x_t - s_t) + (1-\alpha) (\mu_{t-1}+ \xi_{t-1}) \\
        \xi_t &amp;= \beta (\mu_t - \mu_{t-1}) + (1-\beta) \xi_{t-1}
,\\
    s_t &amp;= \gamma (x_t - \mu_t) + (1-\gamma) s_{t-p}.
    \end{aligned}\]</span></p>
<p>Novamente, os parâmetros <span class="math inline">\(\alpha,\beta,\gamma,\mu_0,\xi_0,s_{-p+1},\ldots,s_0\)</span> podem ser obtidos via minimização da soma de quadrados dos erros de previsão.</p>
</section>
<section id="modelo-de-espaço-de-estados-com-inovações" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="modelo-de-espaço-de-estados-com-inovações"><span class="header-section-number">10.4</span> Modelo de espaço de estados com inovações</h2>
<p>O modelo de espaço de estados com inovações é dado por</p>
<p><span class="math display">\[\begin{aligned}x_t&amp;=F'\theta_{t-1}+e_t\\
\theta_t&amp;= G\theta_{t-1}+\psi e_t
\end{aligned}\]</span></p>
<p>onde <span class="math inline">\(F\)</span> e <span class="math inline">\(G\)</span> são matrizes de dimensões condizentes e <span class="math inline">\(e_t\)</span> é a única fonte de erro (ou inovação). Observe que, dado <span class="math inline">\(\mathcal{D}_t\)</span>, temos as seguintes equações para previsão:</p>
<p><span class="math display">\[\begin{aligned}
x_{t+1}&amp;=F'\theta_{t}+e_{t+1}\\
x_{t+2}&amp;=F'\theta_{t+1}+e_{t+2}=F'G\theta_t+F'\psi e_{t+1} + e_{t+2}\\
&amp;=\cdots\\
x_{t+h}&amp;=F'G^{h-1}\theta_t+\sum_{j=1}^{h-1}F'G^{j-1}\psi e_{t+h-j}+e_{t+h}
\end{aligned}\]</span> e, sob a restrição de que <span class="math inline">\(e_t\)</span> é um ruído branco, temos que</p>
<p><span class="math display">\[x_{t+h}|\mathcal{D}_t\sim\hbox{Normal}(f_t(h),Q_t(h)),\]</span> onde <span class="math display">\[\begin{aligned}f_t(h)&amp;=F'G^{h-1}\theta_t\\
Q_t(h)&amp;=\nu\left[1+\sum_{j=1}^{h-1}(F'G^{j-1}\psi)^2\right]
\end{aligned}\]</span></p>
<p>Tanto <span class="math inline">\(\psi\)</span> quanto os eventuais parâmetros em <span class="math inline">\(F\)</span> e <span class="math inline">\(G\)</span> podem ser estimados via método dos mínimos quadrados, minimizando <span class="math display">\[\sum_{t=1}^ne_t^2,\]</span> ou ainda, maximizando <span class="math display">\[\prod_{t=1}^n f(x_t|\mathcal{D}_{t-1})\]</span></p>
<section id="suavização-exponencial-simples-1" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="suavização-exponencial-simples-1"><span class="header-section-number">10.4.1</span> Suavização exponencial simples</h3>
<p>Para o modelo de suavização exponencial, seja <span class="math inline">\(\theta_t=\mu_t\)</span>. Como</p>
<p><span class="math display">\[f_t=\theta_{t-1},\]</span> teremos que <span class="math inline">\(x_t=f_t+e_t\)</span>. Além disso,</p>
<p><span class="math display">\[\begin{aligned}\theta_t&amp;=(1-\alpha)\theta_{t-1}+\alpha x_t\\&amp;=\theta_{t-1}+\alpha e_t\end{aligned}\]</span> onde <span class="math inline">\(\alpha\in(0,1)\)</span>. Portanto, esse modelo pode ser escrito na seguinte forma de espaço estado: <span class="math display">\[\begin{aligned}
x_t&amp;=\theta_{t-1}+e_t\\
\theta_{t}&amp;=\theta_{t-1}+\alpha e_t
\end{aligned}\]</span> logo, identificando <span class="math inline">\(F=1, G=1,\psi=\alpha\)</span>, teremos que</p>
<p><span class="math display">\[\begin{aligned}f_{t}(h)&amp;=\mu_t\\ Q_t(h)&amp;=\nu[1+\alpha^2(h-1)]\end{aligned}\]</span> :::{#exem-}</p>
<p>Considere a série <code>Nile</code>, cujos valores representam o fluxo anual do rio Nilo entre 1871 e 1970. Note que a série aparenta oscilar em torno de dois níveis, separados pelo ano de 1898.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(Nile, <span class="at">ylab =</span> <span class="fu">expression</span>(Fluxo<span class="sc">~</span>em<span class="sc">~</span><span class="dv">10</span><span class="sc">^</span><span class="dv">8</span><span class="sc">~</span>m<span class="sc">^</span><span class="dv">3</span>) , <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">1898</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vamos utilizar a função <code>ets(y, model)</code>, do pacote <code>forecast</code>, onde <code>y</code> é a série temporal e <code>model='ANN'</code> representa o modelo de suavização exponencial.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(forecast)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: forecast</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">ets</span>(Nile, <span class="st">'ANN'</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>mod</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,N,N) 

Call:
ets(y = Nile, model = "ANN")

  Smoothing parameters:
    alpha = 0.2455 

  Initial states:
    l = 1110.6869 

  sigma:  144.2318

     AIC     AICc      BIC 
1458.781 1459.031 1466.597 </code></pre>
</div>
</div>
<p>Acima podemos ver as estimativas dos parâmetros: <span class="math inline">\(\hat{\alpha}=0.2455\)</span>, <span class="math inline">\(\hat{\theta}_0=1110.6869\)</span> e <span class="math inline">\(\nu=144.2318^2\)</span>.</p>
<p>Como de costume, devemos verificar se existem evidências para assumir que o modelo é adequado analisando os resíduos, que podem ser acessados no item <code>$residuals</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> mod<span class="sc">$</span>residuals</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  res
W = 0.99304, p-value = 0.8902</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Pierce test

data:  res
X-squared = 1.7244, df = 1, p-value = 0.1891</code></pre>
</div>
</div>
<p>Os resíduos oscilam em torno de zero e o correlograma não mostra evidências contra a hipótese de ruído branco. O teste Shapiro-Wilk não rejeita a normalidade e o de Box-Pierce não rejeita a hipótese de ruído branco. Portanto, vamos considerar que o modelo é adequado.</p>
<p>Os valores estimados para <span class="math inline">\(\theta_1,\ldots,\theta_n\)</span> podem ser acessados na lista <code>$states</code>, conforme vemos abaixo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(Nile, <span class="at">ylab =</span> <span class="fu">expression</span>(Fluxo<span class="sc">~</span>em<span class="sc">~</span><span class="dv">10</span><span class="sc">^</span><span class="dv">8</span><span class="sc">~</span>m<span class="sc">^</span><span class="dv">3</span>) , <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(mod<span class="sc">$</span>states, <span class="at">col =</span><span class="st">'tomato'</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Por último, podemos realizar previsões com a função <code>forecast</code> conforme ilustramos abaixo para os 5 anos à frente (observe que a previsão é constante, mas, como esperado, sua variância aumenta linearmente ao longo do tempo).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( <span class="fu">forecast</span>(mod, <span class="dv">5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>:::</p>
</section>
<section id="suavização-exponencial-de-holt-1" class="level3" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="suavização-exponencial-de-holt-1"><span class="header-section-number">10.4.2</span> Suavização Exponencial de Holt</h3>
<p>O conjunto de equações acima pode ser reescrito como <span class="math display">\[\begin{aligned*}
    \mu_t &amp;= \mu_{t-1} + \xi_{t-1}+\alpha\left( x_t-\mu_{t-1} - \xi_{t-1}\right)\\&amp;= \tilde{\mu}_{t-1} + \xi_{t-1}+\alpha e_t\\
    \xi_t &amp;= \xi_{t-1}+\beta (\mu_t - \mu_{t-1}-\xi_{t-1}).
    \end{aligned*}\]</span><br>
A partir da primeira equação acima, deduzimos que <span class="math inline">\(\mu_t-\mu_{t-1}-\xi_{t-1}=\alpha e_t\)</span>. Substituindo essa informação na segunda equação teremos <span class="math display">\[\begin{aligned*}
    \mu_t &amp;= \mu_{t-1} + \xi_{t-1}+\alpha e_t\\
    \xi_t &amp;= \xi_{t-1}+\alpha\beta e_t.
    \end{aligned*}\]</span><br>
ou, em forma matricial, <span class="math display">\[\left(\begin{array}{c}\mu_t\\ \xi_t\end{array}\right)=\left(\begin{array}{cc}1 &amp; 1 \\ 0 &amp; 1\end{array}\right)\left(\begin{array}{c}\mu_{t-1}\\ \xi_{t-1}\end{array}\right)+\left(\begin{array}{c}\alpha\\ \alpha\beta\end{array}\right)e_t,\]</span></p>
<p>Note ainda que é possível escrever a equação das observações do modelo em forma matricial: <span class="math display">\[x_{t+h}=\mu_{t+h-1}+\xi_{t+h-1}+e_{t+h-1}=(\begin{array}{cc}1&amp;1\end{array})\left(\begin{array}{c}\mu_{t+h-1}\\ \xi_{t+h-1}\end{array}\right)+e_{t+h}\]</span> Pode-se então mostrar que este modelo possui a seguinte especificação como modelo de espaço estado:</p>
<p><span class="math display">\[\begin{aligned}
F'&amp;=(1\;\; 1)\\
G&amp;=\left(\begin{array}{cc} 1 &amp; 1 \\ 0 &amp; 1\\ \end{array}\right)\\
\theta_t'&amp;=(\mu_t\;\;\xi_t)\\
\psi'&amp;=(\alpha\;\;\alpha\beta)
\end{aligned}\]</span></p>
<p>Desse modo, os parâmetros <span class="math inline">\(\alpha,\beta,\tilde{\mu}_0\)</span> e <span class="math inline">\(\tilde{b}_0\)</span> podem ser obtidos via método de estimação da máxima verossimilhança. Logo, a distribuição da previsão com horizonte <span class="math inline">\(h\)</span> é dada por</p>
<p><span class="math display">\[x_{t+h}|\mathcal{D}_t\sim\hbox{Normal}\left(\mu_t+h\xi_t, \nu\sigma^2_h\right),\]</span> onde <span class="math display">\[\sigma^2_h = 1+(h-1)\left(\alpha^2 + \alpha\beta h + \frac{\beta^2}{6}h(2h-1)\right).\]</span></p>
<div id="exem-">
<p>Abaixo, temos a série do número mensal de homicídios, obtida através do SUS, em Manaus, començando em Janeiro de 1996.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">'https://docs.google.com/spreadsheets/d/1NxxKFzTH7TBd3xP9r5qvggHeorJeR5xKIhn_UZwBol0/edit?usp=sharing'</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> gsheet<span class="sc">::</span><span class="fu">gsheet2tbl</span>(url)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>hom <span class="ot">&lt;-</span> <span class="fu">ts</span>( x<span class="sc">$</span>No, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1996</span>,<span class="dv">1</span>), <span class="at">frequency=</span><span class="dv">12</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(hom, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">xlab =</span> <span class="st">'Ano'</span>, <span class="at">ylab =</span> <span class="st">'No. homicídios'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vamos utilizar a função <code>ets(y, model)</code>, do pacote <code>forecast</code>, onde <code>y</code> é a série temporal e <code>model='AAN'</code> representa o modelo de suavização exponencial de Holt. Vamos adicionar o argumento <code>damped=FALSE</code> - estudaremos esse argumento na seção sobre amortecimento.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(forecast)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">ets</span>(hom, <span class="st">'AAN'</span>, <span class="at">damped =</span> <span class="cn">FALSE</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>mod</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ETS(A,A,N) 

Call:
ets(y = hom, model = "AAN", damped = FALSE)

  Smoothing parameters:
    alpha = 0.3155 
    beta  = 1e-04 

  Initial states:
    l = 41.8223 
    b = 0.3698 

  sigma:  14.4539

     AIC     AICc      BIC 
3609.723 3609.911 3628.626 </code></pre>
</div>
</div>
<p>Acima podemos ver as estimativas dos parâmetros: <span class="math inline">\(\hat{\alpha}=0.3155\)</span>, <span class="math inline">\(\hat{\beta}=0,0001\)</span>, <span class="math inline">\(\mu_0=41,8\)</span>, <span class="math inline">\(\tilde{b}_0=0,369\)</span> e <span class="math inline">\(\nu=14,45^2\)</span>.</p>
<p>Como de costume, devemos verificar se existem evidências para assumir que o modelo é adequado analisando os resíduos, que podem ser acessados no item <code>$residuals</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> mod<span class="sc">$</span>residuals</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  res
W = 0.9652, p-value = 5.27e-07</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Pierce test

data:  res
X-squared = 2.6596, df = 1, p-value = 0.1029</code></pre>
</div>
</div>
<p>Os resíduos oscilam em torno de zero, mas com um aumento progressivo da variância. Embora a hipótese de resíduo branco não seja rejeitada, deve-se considerar esse modelo com cautela. Veremos mais sobre comportamentos dinâmicos da variância no capítulo 15.</p>
<p>Os valores suavizados <span class="math inline">\(\tilde{\mu}_0,\ldots,\tilde{\mu}_t\)</span> podem ser acessados na lista <code>$states</code>, na primeira coluna, conforme vemos abaixo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(hom, <span class="at">ylab =</span> <span class="st">'No. homicídios mensal'</span> , <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(mod<span class="sc">$</span>states[,<span class="dv">1</span>], <span class="at">col =</span><span class="st">'tomato'</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A segunda coluna de <code>$states</code> mostra os valores suavizados para a inclinação.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(mod<span class="sc">$</span>states[,<span class="dv">2</span>], <span class="at">col =</span><span class="st">'tomato'</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">ylab =</span> <span class="st">'Inclinação suavizada'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Por último, podemos realizar previsões com a função <code>forecast</code> conforme ilustramos abaixo para os 6 meses à frente, completando o ano de 2023.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>prev <span class="ot">&lt;-</span> <span class="fu">forecast</span>(mod, <span class="dv">6</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( prev)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="suavização-exponencial-de-holt-winters-1" class="level3" data-number="10.4.3">
<h3 data-number="10.4.3" class="anchored" data-anchor-id="suavização-exponencial-de-holt-winters-1"><span class="header-section-number">10.4.3</span> Suavização Exponencial de Holt-Winters</h3>
<p>Como esperado, esse modelo pode ser reescrito na forma de espaço de estados, considerando o erro de previsão um passo à frente <span class="math inline">\(e_t=x_t-f_t\)</span></p>
<p>As duas primeiras equações de estado são as mesmas do modelo de Holt: <span class="math display">\[\left(\begin{array}{c} \mu_t \\ \xi_t\end{array}\right)=\left(\begin{array}{cc}1 &amp; 1 \\ 0 &amp; 1\end{array}\right)\left(\begin{array}{c} \mu_{t-1} \\ \xi_{t-1}\end{array}\right)+\left(\begin{array}{c} \alpha \\ \alpha\beta\end{array}\right)e_t=G_{\hbox{Holt}}\left(\begin{array}{c} \mu_{t-1} \\ \xi_{t-1}\end{array}\right)+\psi_{\hbox{Holt}}e_t\]</span> Já a terceira equação do modelo pode ser escrita como <span class="math display">\[s_t=s_{t-p}+\gamma e_t.\]</span> Note que essa mesma equação pode ser escrita como <span class="math display">\[\left(\begin{array}{c}s_t\\ s_{t-1} \\ \vdots \\ s_{t-p+1}\end{array}\right)=\underbrace{\left(\begin{array}{c} 0_{p-1'} &amp; 1 \\ \textbf{I}_{p-1} &amp; 0_{p-1} \end{array}\right)}_{P}\left(\begin{array}{c}s_{t-1}\\ s_{t-2} \\ \vdots \\ s_{t-p}\end{array}\right)+\gamma \boldsymbol{E}_{p}e_t\]</span> onde <span class="math inline">\(\boldsymbol{E}_p'=(1,0,\ldots,0)\)</span>. A matriz <span class="math inline">\(P\)</span> dada acima é uma matriz do tipo permutação. Essa em particular coloca o elemento da última coordenada na primeira e faz com que todos os outros elementos seja alocados uma coordenada a frente. Fazendo <span class="math inline">\(\theta_0'=(\mu_0,\xi_0,s_{1-p},\ldots,s_0)\)</span> teremos que o modelo de Holt-Winter na forma de espaço estado é dado por</p>
<p><span class="math display">\[\begin{aligned}
x_t&amp;=\left(\begin{array}{cc|cccc}1&amp;1&amp;0&amp;0&amp;\cdots&amp;1\end{array}\right)\theta_{t-1}+e_t\\
\theta_t&amp;=\left(\begin{array}{c|c}G_{\hbox{Holt}} &amp; 0_{2\times p}\\ \hline
0_{p\times 2} &amp; P\end{array}\right)\theta_{t-1}+\left(\begin{array}{c}\alpha \\ \alpha\beta \\ \hline \gamma1_p \end{array}\right)e_t\end{aligned}\]</span></p>
<div id="exem-">
<p>Considere novamente a série <code>co2</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">ets</span>(co2, <span class="at">model =</span> <span class="st">'AAA'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Abaixo, seguem os gráfico da decomposição através do modelo de Holt-Winter com a normalização.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(co2, mod<span class="sc">$</span>states[,<span class="dv">1</span>][<span class="sc">-</span><span class="dv">1</span>], mod<span class="sc">$</span>states[,<span class="dv">2</span>][<span class="sc">-</span><span class="dv">1</span>], mod<span class="sc">$</span>states[,<span class="dv">3</span>][<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(x) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Série original'</span>,<span class="st">'Nível'</span>, <span class="st">'Inclinação'</span>,<span class="st">'Sazonalidade'</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A análise dos resíduos, mostrada abaixo, mostra que o modelo está bem ajustado ao conjunto de dados.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> mod<span class="sc">$</span>residuals</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ts.plot</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  res
W = 0.99742, p-value = 0.6848</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Pierce test

data:  res
X-squared = 2.8016, df = 1, p-value = 0.09417</code></pre>
</div>
</div>
</div>
</section>
</section>
<section id="exercício" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="exercício"><span class="header-section-number">10.5</span> Exercício</h2>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 10.1</strong></span> A série abaixo aparesenta o número mensal de nascidos vivos no Amazonas desde janeiro de 1994.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">'https://docs.google.com/spreadsheets/d/1KvXQUmIj29_CYx14KfE6NjkLYajvnw7SEyFg5vSsfQM/edit?usp=sharing'</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> gsheet<span class="sc">::</span><span class="fu">gsheet2tbl</span>(url)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol type="a">
<li><p>Ajuste um modelo de suavização exponencial adequado e analise suas componentes.</p></li>
<li><p>Em 2024 foram observados os nascimentos mensais abaixo. Verifique se o seu modelo consegue prever de modo adequado esse ano.</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5635</span>,<span class="dv">5065</span>,<span class="dv">5556</span>,<span class="dv">5287</span>,<span class="dv">5421</span>,<span class="dv">5219</span>,<span class="dv">5314</span>,<span class="dv">5666</span>,<span class="dv">5814</span>,<span class="dv">5851</span>,<span class="dv">5483</span>,<span class="dv">5639</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="para-outro-curso" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="para-outro-curso"><span class="header-section-number">10.6</span> Para outro curso…</h2>
<section id="modelo-de-holt-amortecido" class="level3" data-number="10.6.1">
<h3 data-number="10.6.1" class="anchored" data-anchor-id="modelo-de-holt-amortecido"><span class="header-section-number">10.6.1</span> Modelo de Holt amortecido</h3>
<p>Considere que a previsão um passo à frente é dada por, <span class="math display">\[f_{t}(1)=\mu_{t-1}+\phi\tilde{b}_{t-1}=(1\;\;\phi)\left(\begin{array}{c}\tilde{\mu}_{t-1}\\ \tilde{b}_{t-1}\end{array}\right)\]</span> onde <span class="math inline">\(\phi\in(0,1)\)</span> tem o objetivo de amortecer a tendência dada pelo método de Holt, criando um previsão não linear. Com isso, teremos <span class="math display">\[\begin{aligned}
\mu_t &amp;= \alpha x_t + (1-\alpha)(\mu_{t-1} + \phi\xi_{t-1})\\
\tilde{b}_t &amp;= \beta(\tilde{\mu}_{t} - \tilde{\mu}_{t-1})+(1-\beta) \phi\tilde{b}_{t-1}
\end{aligned}\]</span> que por sua vez pode ser reescrita como <span class="math display">\[\begin{aligned}
\left(\begin{array}{c}\tilde{\mu}_t\\ \tilde{b}_t\end{array}\right) &amp;= \left(\begin{array}{cc}1&amp;\phi\\ 0 &amp;\phi\end{array}\right)\left(\begin{array}{c}\tilde{\mu}_{t-1}\\ \tilde{b}_{t-1}\end{array}\right)+\left(\begin{array}{c}\alpha_t\\ \alpha\beta\end{array}\right)e_t\end{aligned}\]</span> e, identificando a matriz acima com o termo <span class="math inline">\(\phi\)</span> como <span class="math inline">\(G\)</span>, teremos que <span class="math display">\[\hat{y}_{t}(h)=F'G^{h-1}\theta_{t}=\tilde{\mu}_t+(\phi+\cdots+\phi^h)\tilde{b}_t\]</span> Abaixo, segue um esboço dessa função para alguns valores de <span class="math inline">\(\phi.\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="suave_exponencial_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="modelos-com-componentes-multiplicativas" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="modelos-com-componentes-multiplicativas"><span class="header-section-number">10.7</span> Modelos com componentes multiplicativas</h2>
<section id="tendência-multiplicativa" class="level3" data-number="10.7.1">
<h3 data-number="10.7.1" class="anchored" data-anchor-id="tendência-multiplicativa"><span class="header-section-number">10.7.1</span> Tendência multiplicativa</h3>
<p>Suponha que <span class="math display">\[\hat{y}_t(h)=\tilde{\mu}_t\tilde{b}_t^h\]</span> o que implica que o logaritmo de <span class="math inline">\(y_t\)</span> possui tendência localmente linear. Podemos adaptar o método de Holt, suavizando, como de costume, <span class="math inline">\(\tilde{\mu}_t\)</span> por <span class="math display">\[\begin{aligned}\tilde{\mu}_t&amp;=\alpha y_t+(1-\alpha)\hat{y}_{t-1}(1)\\
&amp;=\alpha\tilde{\mu}_{t}+(1-\alpha)\tilde{\mu}_{t-1}\tilde{b}_{t-1}\end{aligned}\]</span></p>
<p>Além disso, como o logaritmo da tendência é localmente linear, teremos que <span class="math display">\[\log \tilde{\mu}_t-\log\tilde{\mu}_{t-1}\approx \log\tilde{b}_t\]</span> ou ainda <span class="math display">\[\tilde{b}_t\approx \frac{\tilde{\mu}_t}{\tilde{\mu}_{t-1}},\]</span> logo, considerando que <span class="math inline">\(\tilde{b}_t\approx \tilde{b}_{t-1}\)</span>, podemos suavizar <span class="math inline">\(b_t\)</span> do seguinte modo: <span class="math display">\[\tilde{b}_t=\beta\frac{\tilde{\mu}_t}{\tilde{\mu}_{t-1}}+(1-\beta)\tilde{b}_{t-1}.\]</span> Deste modo, o modelo com tendência multiplicativa é dado por <span class="math display">\[\begin{aligned}
\tilde{\mu}_t&amp;=\alpha y_t+(1-\alpha)\tilde{\mu}_{t-1}\tilde{b}_{t-1}\\
\tilde{b}_t&amp;=\beta\frac{\tilde{\mu}_t}{\tilde{\mu}_{t-1}}+(1-\beta)\tilde{b}_{t-1}
\end{aligned}\]</span> e, na forma de modelo de espaço estado,</p>
<p><span class="math display">\[\begin{aligned}
y_t&amp;=\tilde{\mu}_{t-1}\tilde{b}_{t-1}+e_t\\
\tilde{\mu}_t&amp;=\tilde{\mu}_{t-1}\tilde{b}_{t-1}+\alpha e_t\\
\tilde{b}_t&amp;=\tilde{b}_{t-1}+\alpha\beta\frac{e_t}{\tilde{\mu}_{t-1}}
\end{aligned}\]</span></p>
<p>As estimativas de máxima verossimilhança para <span class="math inline">\(\tilde{\mu}_0,\alpha,\nu\)</span> são obtidas via maximização da função de verossimilhança, conforme visto na introdução. Já a distribuição da função de previsão</p>
<p>Note que também existe uma versão deste modelo com o amortecedor. Supondo que <span class="math display">\[\log \hat{y}_t(h)=\log(\tilde{\mu}_{t-1})+(\phi+\cdots+\phi^h)\log\tilde{b}_{t-1}\]</span> teremos que a função de previsão com o amortecedor é dada por <span class="math display">\[\hat{y}_t(h)=\tilde{\mu}_{t-1}\tilde{b}_{t-1}^{(\phi+\cdots+\phi^h)}\]</span> que por sua vez possui a seguinte forma em espaço estado:</p>
<p><span class="math display">\[\begin{aligned}
y_t&amp;=\tilde{\mu}_{t-1}\tilde{b}_{t-1}^\phi+e_t\\
\tilde{\mu}_t&amp;=\tilde{\mu}_{t-1}\tilde{b}_{t-1}^\phi+\alpha e_t\\
\tilde{b}_t&amp;=\tilde{b}_{t-1}^\phi+\alpha\beta\frac{e_t}{\tilde{\mu}_{t-1}}
\end{aligned}\]</span></p>
</section>
<section id="tendência-aditiva-e-sazonalidade-multiplicativa" class="level3" data-number="10.7.2">
<h3 data-number="10.7.2" class="anchored" data-anchor-id="tendência-aditiva-e-sazonalidade-multiplicativa"><span class="header-section-number">10.7.2</span> Tendência aditiva e sazonalidade multiplicativa</h3>
<p>teste</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./state_space.html" class="pagination-link" aria-label="Modelos de Espaço de Estados Lineares">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modelos de Espaço de Estados Lineares</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./processo_linear_geral.html" class="pagination-link" aria-label="Modelos ARMA">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modelos ARMA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>